on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12.4
      - run: pip install -U pip
      - run: pip install poetry
      - run: poetry install
      - run: poetry config pypi-token.pypi "$PYPI_TOKEN"
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      - run: poetry publish --build
