on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 3.8.2
          - 3.8.18
          - 3.9.19
          - 3.10.14
          - 3.11.9
          - 3.12.4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - run: pip install -U pip
      - run: pip install poetry
      - run: poetry install
      - run: make lint
      - run: make test-unit